name = "Mac"
version = 0
defaultvariant = "light"
dependencies = [
  "whitesur-icon-theme",
  "whitesur-gtk-theme",
  "apple_cursor",
  "otf-san-francisco",
]

[cursor]
theme = "macOS-Monterey"
size = 16

[font]
name = "SF Pro Display"
size = 10

[icons]
light = "WhiteSur"
dark = "WhiteSur-dark"

[gtk]
[gtk.light]
theme = "WhiteSur-Light"
[gtk.dark]
theme = "WhiteSur-Dark"

