---
theme:
  name: arc
  cursor: elementary-instantos
  gtk:
    font:
        name: Cantarell
        size: 10
        googlesource: Cantarell
    icons:
        name: Papirus
        gitsource: PapirusDevelopmentTeam/papirus-icon-theme
    theme:
        name: Arc
        pacmansource: arc-gtk-theme
    dark:
      theme: Arc-Dark
      icons: Papirus-dark
