---
theme:
    name: dracula
    cursor: paper-instantos
    gtk:
        font:
            name: Roboto
            size: 10
            googlesource: Roboto
        icons:
            name: materiacula
        theme:
            name: materiacula
            gitsource: paperbenni/materiacula
