name = "dracula"
version = 1
defaultvariant = "dark"
dependencies = [
    "dracula-icons-git",
    "instantcursors",
    "ttf-roboto",
    "dracula-gtk-theme"
]

[font]
name = "Roboto"
size = 13


[cursor]
theme = "paper-instantos"
size = 16

[icons]
light = "Dracula"
dark = "Dracula"

[gtk]
[gtk.dark]
theme = "Dracula"

[gtk.light]
theme = "Dracula"

[colors]
background = "#282A36"
accent = "#FF79C6"

# // TODO: 
# // add asset submodule
# //            gitsource: paperbenni/materiacula
# 
