name = "instantOS"
version = 1
defaultvariant = "light"
dependencies = [
  "papirus-icon-theme",
  "instantcursors",
  "inter-font",
  "qogir-gtk-theme"
]

[cursor]
theme = "elementary-instantos"
size = 16

[font]
name = "Inter"
size = 12

[icons]
light = "Papirus"
dark = "Papirus-Dark"

[gtk]
[gtk.light]
theme = "Qogir"
[gtk.dark]
theme = "Qogir-dark"

# kvantum tends to be a bit buggy, not enabled by default
# [qt]
# kvantum = "Qogir"
# [qt.light]
# theme = "kvantum"
# [qt.dark]
# theme = "kvanum-dark"


[colors]
background = "#121212"
accent = "#88B2F6"



