name = "instantOS"
version = 0
defaultvariant = "light"
dependencies = ["materia-gtk-theme", "papirus-icon-theme", "instantcursors", "inter-font"]

[cursor]
theme = "elementary-instantos"
size = 16

[font]
name = "Inter"
size = 12

[icons]
light = "Papirus"
dark = "Papirus-Dark"

[gtk]
[gtk.light]
theme = "Qogir"
[gtk.dark]
theme = "Qogir-dark"

[qt]
[qt.light]
theme = "kvantum"
[qt.dark]
theme = "kvanum-dark"

kvantum = "Materia"

[colors]
background = "#121212"
accent = "#88B2F6"



